title: "Bernhard Pfann"

logo: "/images/logo.png?raw=true"

description: <br>Finance professional tapping into data science. Passionate about turning data into insights and translating code into business terms.
  <br>
  <br>
  <img src="images/linkedin.svg">
  
  <a href="https://github.com/bernhard-pfann">View My Github Profile</a><br>
  <a href="https://www.linkedin.com/in/bernhard-pfann/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
