title: 
  <p align="center">
    Bernhard Pfann
  </p>

logo: 
  <p align="center">
    "/images/logo.png?raw=true"
  </p>

description:
  <p align="center"><br>
    Finance professional tapping into data science | MSc Business Analytics | MSc Finance
  </p>

  <br><br>
  <a href="https://github.com/bernhard-pfann">View My Github Profile</a><br>
  <a href="https://www.linkedin.com/in/bernhard-pfann/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
